Galran/new emitter
microsoft/OpticSim.jl pull request #47
Opened 2021-03-24 01:19 UTC by galran

Added the new emitters implementation and some Pluto Notebooks utilities and examples.

2021-03-24 06:25 UTC, BrianGun approved these changes

2021-03-24 12:04 UTC, alfredclwong requested changes
This is a big PR so I have a lot of review comments. If the tone seems terse it's for the sake of brevity: nothing personal! Here goes...

https://github.com/microsoft/OpticSim.jl/pull/47/commits/16e5de40904962daa987f628f00355bb93fb6925

**OpticSim.jl**
What do you mean by "a better approch to how and where visualization code should reside"? Would you prefer for visualization code to be local to the corresponding logical code? I'm not sure this is a good idea.

**Emitter4.jl**
There are a lot of generic utility definitions, e.g. `MissingImplementationException`, `@timeCap`, etc. Could you move these out of the submodule?

Along the same lines, shouldn't Emitters.Geometry and Emitters.Visualization be merged with the existing OpticSim submodules?

There is a switch from relative imports (`import ..OpticSim`) in `OpticSim.Emitters` to `import OpticSim` in the triple nested submodules (e.g. `OpticSim.Emitters.Geometry`). This seems inconsistent - is `import ...OpticSim` possible?

`unitX`/`unitY`/`unitZ` are defined in the local scope, but `OpticSim.origin` is defined in `OpticSim`. Why?

Is it necessary to force a specific type (via `::Type{T} = Float64`) in `rotXmat` etc.? This seems to defeat the purpose of parametric typing.

On the other hand, `Emitters.generate(s::Uniform{T}) where {T}` (L304) is missing some type checking: `T<:Real` seems minimal. And `Base.length(d::Constant{T}) where {T} = 1` (L430) doesn't use `T` - in this case, it's possible to omit `T` and get the same effect.

Aside from additional constructors, what's the difference between `Origins.Point` (L597) and `Geometry.Vec3D`?

Could you write docstrings for the new definitions? We definitely want information on Emitters in the auto-generated documentation.

https://github.com/microsoft/OpticSim.jl/pull/47/commits/63612b9ec0574d8f959aa66ede6a2655d30c9fd8

**Project.toml**
[compat] FileIO 1.6 -> 1.4. Was 1.6 causing issues?

**Misc/Misc.jl**
"Misc" is ambiguous. Could we instead call the folder something like "Notebook", containing the OpticSim.Notebook module?

**NotebooksUtils.jl**
Abbreviation (NB) is discouraged in Julia - better to use `const NB = OpticSim.Notebook` to define an alias. 

https://github.com/microsoft/OpticSim.jl/pull/47/commits/7175e188ba2629d9d4dad80bc0c9f1a3077aa439 (merge commit)

**Project.toml**
[compat] HTTP 0.9 -> 0.8. Why?

Tests! OpticSim is currently ~6000 LOC (lines of code), and Emitter4.jl alone is ~1000 untested LOC. This will drop our coverage way down to ~40%.

The #region comment blocks are pretty nifty. However, I think these represent natural splits into separate source files. Splitting achieves the same goal (encapsulation) in a more explicit and maintainable manner. Since Emitters is now a (large) submodule, these files would go in a folder Optical/Emitters/.

2021-03-24 16:52 UTC, galran commented
Lots of good comments 😊
I’m still figuring out some of them myself. I think Visualization needs to be as local as possible and I also think we should create a mechanism to localize the tests too using some consistent interfaces.
I think the CSG and Emitters Geometry should be merged asap.
There is a switch from relative imports (import ..OpticSim) in OpticSim.Emitters to import OpticSim in the triple nested submodules (e.g. OpticSim.Emitters.Geometry). This seems inconsistent - is import ...OpticSim possible? CORRECT!

…and so on…Just need more time lol

ran



From: Alfred Wong ***@***.***>
Sent: Wednesday, March 24, 2021 5:05 AM
To: microsoft/OpticSim.jl ***@***.***>
Cc: Ran Gal ***@***.***>; Author ***@***.***>
Subject: Re: [microsoft/OpticSim.jl] Galran/new emitter (#47)


@alfredclwong requested changes on this pull request.

This is a big PR so I have a lot of review comments. If the tone seems terse it's for the sake of brevity: nothing personal! Here goes...

16e5de4<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FOpticSim.jl%2Fcommit%2F16e5de40904962daa987f628f00355bb93fb6925&data=04%7C01%7Crgal%40microsoft.com%7C4406350e1fe14392574208d8eebd0a66%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637521842986047879%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2qbK3Om2BBZUu4rqsQ0KhUuVyezpqmrnn4C88gnj5I0%3D&reserved=0>

OpticSim.jl
What do you mean by "a better approch to how and where visualization code should reside"? Would you prefer for visualization code to be local to the corresponding logical code? I'm not sure this is a good idea.

Emitter4.jl
There are a lot of generic utility definitions, e.g. MissingImplementationException, @timeCap, etc. Could you move these out of the submodule?

Along the same lines, shouldn't Emitters.Geometry and Emitters.Visualization be merged with the existing OpticSim submodules?

There is a switch from relative imports (import ..OpticSim) in OpticSim.Emitters to import OpticSim in the triple nested submodules (e.g. OpticSim.Emitters.Geometry). This seems inconsistent - is import ...OpticSim possible?

unitX/unitY/unitZ are defined in the local scope, but OpticSim.origin is defined in OpticSim. Why?

Is it necessary to force a specific type (via ::Type{T} = Float64) in rotXmat etc.? This seems to defeat the purpose of parametric typing.

On the other hand, Emitters.generate(s::Uniform{T}) where {T} (L304) is missing some type checking: T<:Real seems minimal. And Base.length(d::Constant{T}) where {T} = 1 (L430) doesn't use T - in this case, it's possible to omit T and get the same effect.

Aside from additional constructors, what's the difference between Origins.Point (L597) and Geometry.Vec3D?

Could you write docstrings for the new definitions? We definitely want information on Emitters in the auto-generated documentation.

63612b9<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FOpticSim.jl%2Fcommit%2F63612b9ec0574d8f959aa66ede6a2655d30c9fd8&data=04%7C01%7Crgal%40microsoft.com%7C4406350e1fe14392574208d8eebd0a66%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637521842986047879%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=v5Thph4tCiiz1LqNwovPtYK68DPCWoTa77%2FttSLDoOA%3D&reserved=0>

Project.toml
[compat] FileIO 1.6 -> 1.4. Was 1.6 causing issues?

Misc/Misc.jl
"Misc" is ambiguous. Could we instead call the folder something like "Notebook", containing the OpticSim.Notebook module?

NotebooksUtils.jl
Abbreviation (NB) is discouraged in Julia - better to use const NB = OpticSim.Notebook to define an alias.

7175e18<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FOpticSim.jl%2Fcommit%2F7175e188ba2629d9d4dad80bc0c9f1a3077aa439&data=04%7C01%7Crgal%40microsoft.com%7C4406350e1fe14392574208d8eebd0a66%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637521842986057875%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qPLeQK1br93vYwJESLjBEhEEh9ueHQe8cph7j7urU9E%3D&reserved=0> (merge commit)

Project.toml
[compat] HTTP 0.9 -> 0.8. Why?

Tests! OpticSim is currently ~6000 LOC (lines of code), and Emitter4.jl alone is ~1000 untested LOC. This will drop our coverage way down to ~40%.

The #region comment blocks are pretty nifty. However, I think these represent natural splits into separate source files. Splitting achieves the same goal (encapsulation) in a more explicit and maintainable manner. Since Emitters is now a (large) submodule, these files would go in a folder Optical/Emitters/.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FOpticSim.jl%2Fpull%2F47%23pullrequestreview-619636132&data=04%7C01%7Crgal%40microsoft.com%7C4406350e1fe14392574208d8eebd0a66%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637521842986057875%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IFcveQ0tUIQ4tEktx%2BaE45LM%2Bet6VrvGKq88HYaFDa0%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATBK6XUQG44OJKU4FNBT2GTTFHIORANCNFSM4ZWI4SIA&data=04%7C01%7Crgal%40microsoft.com%7C4406350e1fe14392574208d8eebd0a66%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637521842986067873%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FO0hBm4yT0uX1TI0Q8fm2BowBcaK2P5viL6vJFSVYRk%3D&reserved=0>.

2021-03-26 12:34 UTC, alfredclwong commented
I'm beginning work on these changes on the [test/new-emitter](https://github.com/microsoft/OpticSim.jl/tree/test/new-emitter) branch.

2021-03-26 12:34 UTC, closed without merging